name: LinuxBuild
on:
  push:
    branches:
      - 'master'
    tags:
      - v*

env:
  INSTALLPREFIX: "_local"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install gcc g++ git swig python3-dev libssl-dev pkg-config \
            libtool autoconf automake make libglib2.0-dev tcl-dev libpopt-dev \
            libreadline-dev
      - name: Configure
        run: |
          mkdir $INSTALLPREFIX
          ./bootstrap
          ./configure --prefix=$(pwd)/$INSTALLPREFIX/ \
            --with-pythoninstall=$(pwd)/$INSTALLPREFIX/usr/lib/python3 \
            --with-perlinstall=$(pwd)/$INSTALLPREFIX/usr/lib/perl
      - name: Build
        run: |
          make
          make install
          make check
